rcops={
    "Tom Couch": "cceatco",
    "Jo Lampard": "cceajla",
    "Brian Alston": "ccaabaa",
    "Brian Alston": "ucaabaa",
    "Owain Kenway": "uccaoke",
    "Ian Kirker": "uccaiki",
    "Thomas Jones": "ccaathj",
    "William Hay": "ccaawih",
    "Francesco Tusa": "cceaftu",
    "Tony Brown": "ccaatob",
    "James Clements": "ccaajcl",
    "Sam Durrans": "ccaasdu",
    "Clare Gryce": "ccaacla",
    "Luke Sudbery": "ccaalrs",
    "James Hetherington": "ucgajhe",
    "Heather Kelly": "cceahke",
    "Sinan Shi": "cceashi",
    "Raquel Alegre": "ccearal",
    "Mayeul D'Avezac": "cceamda",
    "Jens Nielsen": "cceajhn",
    "Gary Macindoe": "ucakgim",
    "Paul Hajisavvi": "zzaapsh"
    }
